### ISSUE TITLE
baichuan-7b run core dump

### ISSUE THREAD

**Issue by Zjq9409** [intel/xFasterTransformer#210]
```
雨村问：“政公有个衔玉之子，赦公就没一个?”子兴说：“政公有了玉儿，他的妾又生了一个，还没听说是好是歹。赦公也有二子，次子名叫贾琏，今已二十多岁，娶的是政公王夫人的娘家侄女为妻，亲上加亲。这位琏爷捐了个副知府，也不喜读书
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 4463 RUNNING AT qqq-D50DNP1SBB
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
(llm) root@qqq-D50DNP1SBB:~/llm# bash run_benchmark.sh -m baichuan2-7b -d bf16 -s 1 -bs 1 -in 4096 -out 32 -i 3
```

xfastertransformer==1.3.1

**Comment by Duyi-Wang** [comment]
This is because Baichuan2's default set max length is 4096, which you can find `max_pos_seq_len=4096` and `model_max_length=4096` in the `config.ini` file, for benchmarking this file in the example/model_config/baichuan2-7b.
You can just enlarge these two values to work around this issue, but it's not recommended. The Baichuan2 model is trained under this setting, so we can't ensure the generation result if the length is larger than 4096.
