### ISSUE TITLE
using 'cmake ..'  don 't find FindoneCCL.cmake

### ISSUE THREAD

**Issue by 1191569886** [intel/xFasterTransformer#82]
Using 'CMake'
# Build xFasterTransformer
git clone https://github.com/intel/xFasterTransformer.git xFasterTransformer
cd xFasterTransformer
git checkout <latest-tag>
# Please make sure torch is installed when run python example
mkdir build && cd build
cmake ..
make -j

when cmake ..  
--------------------------------------------------
![image](https://github.com/intel/xFasterTransformer/assets/60460362/28627f7c-d846-41fe-81fd-3a033922e99d)
----------------------------------------------------

**Comment by marvin-Yu** [comment]
We encourage you to use Docker to explore the usage of XFT (XFasterTransformer). If you need to compile from source, you can follow the step-by-step instructions provided in our README.md(https://github.com/intel/xFasterTransformer#built-from-source). This error could be due to the absence of the oneCCL dependencies. Please install it and try again.

**Comment by 1191569886** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Duyi-Wang** [comment]
Did you install the oneCCL and source the environment?
If not, you can install oneCCL from source or install oneAPI.
- From source using provided script
```
cd 3rdparty
sh prepare_oneccl.sh
source ./oneCCL/build/_install/env/setvars.sh
```

- From oneAPI following https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html

**Comment by Duyi-Wang** [comment]
oneCCL's dependency has been removed. https://github.com/intel/xFasterTransformer/pull/92
